In [1]:
# Demonstrate use of TensorFlow and PyTorch by implementing simple code in Python

In [2]:
# 1. TensorFlow

In [3]:
import tensorflow as tf

In [4]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(32, )),
    tf.keras.layers.Dense(10, activation='softmax')
])

C:\Users\HP\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [6]:
import numpy as np
x_train = np.random.rand(1000, 32)
y_train = np.random.randint(0, 10, size=(1000,))

In [7]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1012 - loss: 2.3450
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1167 - loss: 2.2956
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step - accuracy: 0.1471 - loss: 2.2767
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1437 - loss: 2.2767
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1268 - loss: 2.2643
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1760 - loss: 2.2494  
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1597 - loss: 2.2514
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.1712 - loss: 2.2381
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1778 - loss: 2.2328  
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1875 - loss: 2.2231


In [8]:
# Other Operations in Tensorflow

In [9]:
import tensorflow as tf
import numpy as np

In [10]:
tensor_from_list = tf.constant([[1, 2], [3, 4]])
print(tensor_from_list)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
random_tensor = tf.random.uniform(shape=(2, 4), minval = 32, maxval = 64)
print(random_tensor)

tf.Tensor(
[[45.95317  38.86329  44.10837  58.355717]
 [60.612442 33.997417 61.56845  37.633694]], shape=(2, 4), dtype=float32)


In [12]:
zero_tensor = tf.zeros(shape=(2, 3))
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [13]:
one_tensor = tf.ones(shape=(2, 3))
print(one_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [14]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.divide(a, b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [15]:
np_arr = np.array([[1, 2], [3, 4]])
tensor_from_np = tf.convert_to_tensor(np_arr)
print(tensor_from_np)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [16]:
# 4. PyTorch

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

In [18]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(32, 64)
        self.fc2 = nn.Linear(64, 10)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

In [19]:
model = SimpleNN()

In [20]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [21]:
x_train = torch.rand(1000, 32)
y_train = torch.randint(0, 10, (1000,))

In [22]:
for epoch in range(10):
    model.train()
    optimizer.zero_grad()
    outputs = model(x_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    print(f'Epoch [{epoch+1}/10], Loss: {loss.item():.4f}')

Epoch [1/10], Loss: 2.3126
Epoch [2/10], Loss: 2.3094
Epoch [3/10], Loss: 2.3065
Epoch [4/10], Loss: 2.3039
Epoch [5/10], Loss: 2.3016
Epoch [6/10], Loss: 2.2996
Epoch [7/10], Loss: 2.2979
Epoch [8/10], Loss: 2.2964
Epoch [9/10], Loss: 2.2951
Epoch [10/10], Loss: 2.2940


In [23]:
# other operations in pytorch

In [24]:
data = [[1, 2], [3, 4]]
tensor_from_list = torch.tensor(data)
print("Tensor from list:\n", tensor_from_list)

random_tensor = torch.rand((2, 3))
print("Random tensor:\n", random_tensor)

zero_tensor = torch.zeros((2, 3))
print("Zero tensor:\n", zero_tensor)

ones_tensor = torch.ones((2, 3))
print("Ones tensor:\n", ones_tensor)

Tensor from list:
 tensor([[1, 2],
        [3, 4]])
Random tensor:
 tensor([[0.0667, 0.0950, 0.4533],
        [0.7571, 0.5881, 0.1029]])
Zero tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [25]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Subtraction:
 tensor([[-4., -4.],
        [-4., -4.]])
Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [26]:
sqrt_tensor = torch.sqrt(a)
print("Square root tensor:\n", sqrt_tensor)

exp_tensor = torch.exp(a)
print("Exponential tensor:\n", exp_tensor)

log_tensor = torch.log(a)
print("Logarithm tensor:\n", log_tensor)

Square root tensor:
 tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])
Exponential tensor:
 tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
Logarithm tensor:
 tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


In [27]:
tensor_np = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
np_array = tensor_np.numpy()  # Convert to NumPy array
print("Converted to NumPy array:\n", np_array)

np_array = np.array([[5.0, 6.0], [7.0, 8.0]])
tensor_from_np = torch.from_numpy(np_array)  # Convert NumPy array to tensor
print("Converted back to Tensor:\n", tensor_from_np)

Converted to NumPy array:
 [[1. 2.]
 [3. 4.]]
Converted back to Tensor:
 tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)
